### ISSUE TITLE
/bin/sh: 1: ./sfdx/install: not found

### ISSUE THREAD

**Issue by vincekruger** [sfdx-actions/setup-sfdx#12]
The SFDX installation started failing last night. :(
Is anyone else experiencing this issue?

```
--2022-03-31 08:07:59--  https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
Resolving developer.salesforce.com (developer.salesforce.com)... 151.
Connecting to developer.salesforce.com (developer.salesforce.com)|151.101.53.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 59976812 (57M) [application/octet-stream]
Saving to: ‘/tmp/sfdx-linux-x64.tar.xz’

2022-03-31 08:08:01 (166 MB/s) - ‘/tmp/sfdx-linux-x64.tar.xz’ saved [59976812/59976812]
/bin/sh: 1: ./sfdx/install: not found
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by nagendraks** [comment]
@fechanique just put a fix by changing the fiile url in index.js, but after that this issue started coming. 

Same here: 

Getting this now after recent fix.

    2022-03-31 08:12:35 (134 MB/s) - ‘/tmp/sfdx-linux-x64.tar.xz’ saved [59976812/59976812]

    /bin/sh: 1: ./sfdx/install: not found

**Comment by vincekruger** [comment]
ok good. It's not just me.  Let me see if I can figure this out and push a PR

**Comment by nagendraks** [comment]
This should be resolved now as per latest push by @fechanique 

https://github.com/sfdx-actions/setup-sfdx/commit/bfa105cedbd5e1e6cd79bfb152144edb2dc040ee

**Comment by vincekruger** [comment]
Magic. Working again. :)
Thanks.
