### ISSUE TITLE
Node.js 12 actions are deprecated. Make the action compatible with latest node version 

### ISSUE THREAD

**Issue by alinawab1** [sfdx-actions/setup-sfdx#15]
We are using node version 16 on our side which is showing this warning. 

Node.js 12 actions are deprecated. For more information see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: sfdx-actions/setup-sfdx@v1

![image](https://user-images.githubusercontent.com/17029179/207862981-7d92e368-3282-4bfd-a97f-25a883961566.png)

The issue seems to be from the hardcoded node version in action.yml and apparently, we cannot change the node version by passing it as a parameters 
![image](https://user-images.githubusercontent.com/17029179/207863539-e1c6b58c-287e-4d1e-9342-228458fa9d50.png)

In our .yml we are calling the action @v1 which seems to be the current stable version, tried @v2 and @v1.2 etc. but that does not seem to be available.

`uses: sfdx-actions/setup-sfdx@v1`

Kindly fix this issue on your end. 
Thanks

**Comment by fechanique** [comment]
fixed
